### ISSUE TITLE
ls /nonexistend_dir doesn't return proper error code

### ISSUE THREAD

**Issue by ruzickap** [micharbet/CLE#67]
Looks like CLE doesn't return proper error code when using `ls` command:

```bash
[0] pruzicka@peru /tmp:$ ls /nonexistent_dir
ls: cannot access '/nonexistent_dir': No such file or directory
[0] pruzicka@peru /tmp:$ ls /nonexistent_dir; echo $?
ls: cannot access '/nonexistent_dir': No such file or directory
2
[0] pruzicka@peru /tmp:$
```

Thanks for looking at it...

**Comment by micharbet** [comment]
Hello,
Thank you for reporting! The issue has been fixed with #68  (stupid error, as usually. It ignored return codes 2-8). Now you can run `cle update` that will download and run new version.

I hope this helps.
And also thank you very much for participation at the workshop!

Kind regards
-michael-
