### ISSUE TITLE
keep the current shell after lsu/lsudo

### ISSUE THREAD

**Issue by vladki77** [micharbet/CLE#80]
Hello Michal,

I have access to a server where the "root" prefers /bin/zsh, and has it in /etc/passwd, while I prefer /bin/bash.

With the old version, when I did lsudo, I had still bash. But with the new version I get zsh and this error:
```
$ lsudo
[sudo] password for vladki: 
[.zshrc]
/var/tmp/root/.zshrc:727: no match
```
And a zsh prompt, not affected by CLE. `/var/tmp/root/.zshrc` is symlink to `/var/tmp/vladki/.cle-vladki/rc-xxxx`

**Comment by micharbet** [comment]
Hi Vladki,
Your issue is caused by my ingenious attempt to make CLE compatible with zsh. It worked for me but later I realized that it doesn't have to all the time. E.g. if a some extensions like ohmyzsh are used.

Fix for you should be quite easy. Try following:
`CLE_ARG='-b'  lsudo`
If this helps, include statement `export CLE_ARG='-b'` into your tweak file

Please let me know if this helped.
I have to anyway remove zsh support from next release. It unfortunately holds me down. Every feature needs to be verified with the other shell while I'm still not sure if it will work in all setups. Also observing a few zsh user I got into impression that they do their very own tweaks.

Cheers
-michael-

**Comment by vladki77** [comment]
Hi Michal,

thank you,  CLE_ARG works well.

Vladki

**Comment by micharbet** [comment]
Thank you for confirmation.
-michael-
